ems/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.views.static import serve
from django.conf import settings
from web.views import depart, user, pnum, task, order, chart, upload

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='media'),

    # 部门管理
    path('depart/list/', depart.depart_list),
    path('depart/add/', depart.depart_add),
    path('depart/batch-add/', depart.depart_batch_add),
    path('depart/del/', depart.depart_del),
    path('depart/<uuid:nid>/edit/', depart.depart_edit),

    # 用户管理
    path('user/list/', user.user_list),
    path('user/add/', user.user_add),
    path('user/del/', user.user_del),
    path('user/<uuid:nid>/edit/', user.user_edit),
    path('login/', user.login),
    path('logout/', user.logout),
    path('login/verify/', user.login_verify),

    # 靓号管理
    path('pnum/list/', pnum.pnum_list),
    path('pnum/add/', pnum.pnum_add),
    path('pnum/<uuid:nid>/edit/', pnum.pnum_edit),
    path('pnum/del/', pnum.pnum_del),

    # 任务管理
    path('task/list/', task.task_list),
    path('task/add/', task.task_add),

    # 订单管理
    path('order/list/', order.order_list),
    path('order/add/', order.order_add),
    path('order/del/', order.order_del),
    path('order/detail/', order.order_detail),
    path('order/edit/', order.order_edit),

    # 数据统计
    path('chart/list/', chart.chart_list),
    path('chart/bar/', chart.chart_bar),
    path('chart/pie/', chart.chart_pie),
    path('chart/line/', chart.chart_line),

    # 上传文件
    path('upload/list/', upload.upload_list),
    path('upload/form/', upload.upload_form),
    path('upload/modelform/', upload.upload_modelform),
]

web/models.py
from django.db import models
import uuid
from datetime import datetime


# Create your models here.

class Department(models.Model):
    """ 部门表 """
    id = models.UUIDField(verbose_name="id", primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    title = models.CharField(verbose_name="部门名称", max_length=32)
    logo = models.FileField(verbose_name="logo", max_length=128, upload_to='depart_logo')

    def __str__(self):
        return self.title


class UserInfo(models.Model):
    """ 员工表 """
    id = models.UUIDField(verbose_name="id", primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    account = models.CharField(verbose_name="用户名", max_length=16)
    name = models.CharField(verbose_name="姓名", max_length=16)
    gender_choice = (
        (1, "男"),
        (2, "女"),
    )
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choice)
    pwd = models.CharField(verbose_name="密码", max_length=64)
    balance = models.DecimalField(verbose_name="账户余额", max_digits=10, decimal_places=2, default=0)
    create_time = models.DateTimeField(verbose_name="创建时间", default=datetime.now)
    # 级联删除
    depart = models.ForeignKey(verbose_name="部门", to="Department", to_field="id", on_delete=models.CASCADE)
    admin_choice = (
        (0, "否"),
        (1, "是")
    )
    admin = models.PositiveSmallIntegerField(verbose_name="管理员", choices=admin_choice)

    def __str__(self):
        return self.name


class PrettyNum(models.Model):
    """ 商品：靓号表 """
    id = models.UUIDField(verbose_name="id", primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    mobile = models.CharField(verbose_name="号码", max_length=11)
    price = models.DecimalField(verbose_name="价格", max_digits=10, decimal_places=2, default=0)
    level_choice = (
        (1, "银"),
        (2, "金"),
        (3, "铂金"),
        (4, "钻石"),
    )
    level = models.PositiveSmallIntegerField(verbose_name="级别", choices=level_choice)
    status_choice = (
        (0, "未启用"),
        (1, "启用"),
    )
    status = models.PositiveSmallIntegerField(verbose_name="状态", choices=status_choice, default=0)


class Task(models.Model):
    """ 任务列表 """
    id = models.UUIDField(verbose_name="id", primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    level_choice = {
        (1, "普通"),
        (2, "重要"),
        (3, "临时")
    }
    level = models.PositiveSmallIntegerField(verbose_name="级别", choices=level_choice, default=1)
    title = models.CharField(verbose_name="标题", max_length=12)
    detail = models.TextField(verbose_name="详细信息")
    user = models.ForeignKey(verbose_name="负责人", to="UserInfo", on_delete=models.CASCADE)


class Order(models.Model):
    """ 订单 """
    id = models.UUIDField(verbose_name="id", primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    oid = models.CharField(verbose_name="订单号", max_length=32)
    title = models.CharField(verbose_name="名称", max_length=16)
    price = models.PositiveIntegerField(verbose_name="价格")
    status_choice = (
        (1, "已支付"),
        (2, "未支付")
    )
    status = models.PositiveSmallIntegerField(verbose_name="状态", choices=status_choice, default=2)
    user = models.ForeignKey(verbose_name="用户", to=UserInfo, on_delete=models.CASCADE)


class Avatar(models.Model):
    """ 混合上传（表单数据与文件） """
    id = models.UUIDField(verbose_name="id", primary_key=True, default=uuid.uuid4, editable=False, unique=True)
    name = models.CharField(verbose_name="姓名", max_length=32)
    age = models.PositiveSmallIntegerField(verbose_name="年龄")
    avatar = models.FileField(verbose_name="头像", max_length=128, upload_to='avatar/')

web/views/upload.py
import os
from django.shortcuts import render
from django.http import HttpResponse
from web import models
from web.utils.form import UploadForm, UploadModelForm


def upload_list(request):
    if request.method == 'GET':
        return render(request, 'upload_list.html')
    file_obj = request.FILES.get("file")
    # 以二进制写入模式打开文件对象
    file = open(file_obj.name, mode='wb')
    # 块模式写入到服务端中
    for chunk in file_obj.chunks():
        file.write(chunk)
    file.close()
    return HttpResponse("文件上传成功")


def upload_form(request):
    title = "Form上传"
    if request.method == 'GET':
        form = UploadForm()
        context = {
            'title': title,
            'form': form
        }
        return render(request, 'upload_form.html', context)

    form = UploadForm(data=request.POST, files=request.FILES)
    if form.is_valid():
        # 1. 读取文件名，写入文件夹并获取写入路径
        avatar_obj = form.cleaned_data.get("avatar")
        media_path = os.path.join("media", "avatar", avatar_obj.name)
        f = open(media_path, mode='wb')
        for chunk in avatar_obj.chunks():
            f.write(chunk)
        f.close()

        # 2. 将图片路径写入数据库
        models.Avatar.objects.create(
            name=form.cleaned_data['name'],
            age=form.cleaned_data['age'],
            avatar=media_path
        )
        return HttpResponse("添加成功")

    context = {
        'title': title,
        'form': form
    }
    return render(request, 'upload_form.html', context)


def upload_modelform(request):
    title = "ModelForm上传"
    if request.method == 'GET':
        form = UploadModelForm()
        context = {
            'title': title,
            'form': form
        }
        return render(request, 'upload_modelform.html', context)
    form = UploadModelForm(data=request.POST, files=request.FILES)
    if form.is_valid():
        form.save()
        return HttpResponse("上传成功")
    context = {
        'title': title,
        'form': form
    }
    return render(request, 'upload_modelform.html', context)

web/templates/add.html
<!-- 新建数据公共组件 /-->
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{{ title }}</h3>
        </div>
        <div class="panel-body">
            <form method="post">
                {% csrf_token %}
                {% for fields in form %}
                    <div class="form-group">
                        <label>{{ fields.label }}</label>
                        {{ fields }}
                        <span style="color: red">{{ fields.errors }}</span>
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">提 交</button>
            </form>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script>
        $(function () {
            $('#id_create_time').datepicker({
                format: 'yyyy-mm-dd',
                startDate: '0',
                language: 'zh-CN',
                autoclose: true
            });
        })
    </script>
{% endblock %}

web/templates/edit.html
<!-- 编辑数据公共组建 /-->
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{{ title }}</h3>
        </div>
        <div class="panel-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for fields in form %}
                    <div class="form-group">
                        <label>{{ fields.label }}</label>
                        {{ fields }}
                        <span style="color: red">{{ fields.errors }}</span>
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">提 交</button>
            </form>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script>
        $(function () {
            $('#id_create_time').datepicker({
                format: 'yyyy-mm-dd',
                startDate: '0',
                language: 'zh-CN',
                autoclose: true
            });
        })
    </script>
{% endblock %}

web/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .navbar {
            border-radius: 0;
        }
    </style>
    {% block css %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">部门管理中心</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/depart/list/">部门管理</a></li>
                <li><a href="/user/list/">用户管理</a></li>
                <li><a href="/pnum/list/">靓号管理</a></li>
                <li><a href="/task/list/">任务管理</a></li>
                <li><a href="/order/list/">订单管理</a></li>
                <li><a href="/chart/list/">数据统计</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">上传功能<span class="caret"></span></a>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                        <li><a href="/upload/list/">文件上传</a></li>
                        <li><a href="/upload/form/">form上传</a></li>
                        <li><a href="/upload/modelform/">modelform上传</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">{{ request.session.login_info.name }}<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">用户信息</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="/logout/">注销</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</div>

<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
{% block js %}{% endblock %}
</body>
</html>

web/templates/layout_add.html
<!-- 新建数据公公组建 /-->
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{{ title }}</h3>
        </div>
        <div class="panel-body">
            <form method="post">
                {% csrf_token %}
                {% for fields in form %}
                    <div class="form-group">
                        <label>{{ fields.label }}</label>
                        {{ fields }}
                        <span style="color: red">{{ fields.errors }}</span>
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">提 交</button>
            </form>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script>
        $(function () {
            $('#id_create_time').datepicker({
                format: 'yyyy-mm-dd',
                startDate: '0',
                language: 'zh-CN',
                autoclose: true
            });
        })
    </script>
{% endblock %}

web/templates/order_list.html
{% extends 'search.html' %}

{% block content %}
    <div style="margin-bottom: 10px">
        <input id="btnAdd" type="button" value="新建订单" class="btn btn-primary">
    </div>
    <!-- 新建/编辑数据对话框 -->
    <div class="modal fade" id="orderInfo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">新建订单</h4>
                </div>
                <div class="modal-body">
                    <form id="formAdd">
                        <div class="clearfix">
                            {% for obj in form %}
                                <div class="col-xs-6">
                                    <div class="form-group" style="position: relative;margin-bottom: 25px">
                                        <label>{{ obj.label }}</label>
                                        {{ obj }}
                                        <span class="error-msg" style="color: red; position: absolute;"></span>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
                    <button id="btnSave" type="button" class="btn btn-primary">保 存</button>
                </div>
            </div>
        </div>
    </div>
    <!-- 显示数据 -->
    <div class="panel panel-default">
        <div class="panel-heading">
            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            订单列表
        </div>

        <!-- Table -->
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>序号</th>
                <th>订单号</th>
                <th>订单名称</th>
                <th>价格</th>
                <th>所属用户</th>
                <th>状态</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in queryset %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ obj.oid }}</td>
                    <td>{{ obj.title }}</td>
                    <td>{{ obj.price }}</td>
                    <td>{{ obj.user }}</td>
                    <td>{{ obj.get_status_display }}</td>
                    <td>
                        <input uid="{{ obj.id }}" class="btn btn-primary btn-xs btn-edit" type="button" value="编辑">
                        <input uid="{{ obj.id }}" class="btn btn-danger btn-xs btn-del" type="button" value="删除">
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- 删除对话框 -->
    <div class="modal fade" id="delModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="alert alert-danger alert-dismissible fade in" role="alert">
                <h4>是否删除此条数据？</h4>
                <p style="text-align: right;">
                    <button id="btnConfirmDelete" type="button" class="btn btn-danger">确 定</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
                </p>
            </div>
        </div>
    </div>
    <!-- 分页组件 -->
    <ul class="pagination" style="float: left;">
        {{ page_number }}
    </ul>

{% endblock %}

{% block js %}
    <script type="text/javascript">
        var DELETE_ID;
        var EDIT_ID;

        $(function () {
            bindBtnAddEvent();
            bindBtnSaveEvent();
            bindBtnDelEvent();
            bindBtnConfirmDeleteEvent();
            bindBtnEditEvent();
        })

        function bindBtnAddEvent() {
            $("#btnAdd").click(function () {
                EDIT_ID = undefined;
                // 修改标题
                $('#myModalLabel').text("新建订单");
                // 清空对话框中的数据
                $('#formAdd')[0].reset();
                // 点击新建按钮，显示对话框
                $('#orderInfo').modal('show');
            });
        }

        function bindBtnSaveEvent() {
            $("#btnSave").click(function () {
                $('.error-msg').empty();
                if (EDIT_ID) {
                    doEdit();
                } else {
                    doAdd();
                }
            });
        }

        function doEdit() {
            $.ajax({
                url: "/order/edit/?uid=" + EDIT_ID,
                type: "post",
                data: $('#formAdd').serialize(),
                dataType: "JSON",
                success: function (res) {
                    // console.log(res)
                    if (res.status) {
                        // alert("创建成功");
                        // 清空表单数据
                        $('#formAdd')[0].reset();
                        // 关闭对话框
                        $('#newOrder').modal('hide');
                        // 刷新页面
                        location.reload();
                    } else {
                        if (res.tips) {
                            alert(res.tips)
                        } else {
                            $.each(res.error, function (k, v) {
                                $('#id_' + k).next().text(v[0]);
                            })
                        }
                    }
                }
            })
        }

        function doAdd() {
            $.ajax({
                url: "/order/add/",
                type: "post",
                data: $('#formAdd').serialize(),
                dataType: "JSON",
                success: function (res) {
                    // console.log(res)
                    if (res.status) {
                        // alert("创建成功");
                        // 清空表单数据
                        $('#formAdd')[0].reset();
                        // 关闭对话框
                        $('#newOrder').modal('hide');
                        // 刷新页面
                        location.reload();
                    } else {
                        $.each(res.error, function (k, v) {
                            $('#id_' + k).next().text(v[0]);
                        })
                    }
                }
            })
        }

        function bindBtnDelEvent() {
            $('.btn-del').click(function () {
                // alert("点击了删除");
                $('#delModal').modal('show');

                // 获取当前行的ID
                DELETE_ID = $(this).attr("uid");
            });
        }

        function bindBtnConfirmDeleteEvent() {
            $('#btnConfirmDelete').click(function () {
                // 点击确认删除按钮，将全局变量DELETE_ID 发送到后台
                $.ajax({
                    url: "/order/del/",
                    type: "GET",
                    data: {
                        'uid': DELETE_ID
                    },
                    dataType: 'JSON',
                    success: function (res) {
                        if (res.status) {
                            location.reload()
                        }
                    }
                })
            });
        }

        function bindBtnEditEvent() {
            $('.btn-edit').click(function () {
                var currentID = $(this).attr('uid')
                EDIT_ID = currentID;
                $.ajax({
                    url: "/order/detail/",
                    type: 'get',
                    data: {
                        uid: currentID,
                    },
                    dataType: 'JSON',
                    success: function (result) {
                        if (result.status) {
                            // 清空对话框中的数据
                            $('#formAdd')[0].reset();
                            // 将数据赋值给标签
                            $.each(result.data, function (k, v) {
                                $('#id_' + k).val(v);
                            })
                            // 修改对话框标题
                            $('#myModalLabel').text("编辑订单");
                            // 发送ajax向后台获取当前行的数据
                            $('#orderInfo').modal('show');
                        } else {
                            alert(result.error);
                        }
                    }
                })
            })
        }
    </script>
{% endblock %}

web/templates/pnum_list.html
{% extends 'search.html' %}

{% block content %}
    <div style="margin-bottom: 10px">
        <a class="btn btn-success" href="/pnum/add/">
            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
            新建靓号
        </a>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            靓号列表
        </div>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>序号</th>
                <th>靓号</th>
                <th>等级</th>
                <th>价格</th>
                <th>状态</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in queryset %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ obj.mobile }}</td>
                    <td>{{ obj.get_level_display }}</td>
                    <td>{{ obj.price }}</td>
                    <td>{{ obj.get_status_display }}</td>
                    <!-- 编辑操作 -->
                    <td>
                        <a class="btn btn-primary btn-xs" href="/pnum/{{ obj.id }}/edit/">编辑</a>
                        <a class="btn btn-danger btn-xs" href="/pnum/del/?nid={{ obj.id.hex }}">删除</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="clearfix">
        <ul class="pagination" style="float: left;">
            {{ page_number }}
        </ul>
    </div>
{% endblock %}

web/templates/task_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">新建任务表单</div>
        <div class="panel-body">
            <form id="formAdd">
                <div class="clearfix">
                    {% for obj in form %}
                        <div class="col-xs-6">
                            <div class="form-group" style="position: relative;margin-bottom: 25px">
                                <label>{{ obj.label }}</label>
                                {{ obj }}
                                <span class="error-msg" style="color: red; position: absolute;"></span>
                            </div>
                        </div>
                    {% endfor %}
                    <div class="col-xs-12">
                        <button id="btnAdd" type="button" class="btn btn-primary">提交</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            已有任务
        </div>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>序号</th>
                <th>任务名称</th>
                <th>任务级别</th>
                <th>任务详情</th>
                <th>指派给</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in queryset %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ obj.title }}</td>
                    <td>{{ obj.get_level_display }}</td>
                    <td>{{ obj.detail }}</td>
                    <td>{{ obj.user }}</td>
                    <!-- 编辑操作 -->
                    <td>
                        <a class="btn btn-primary btn-xs" href="#">编辑</a>
                        <a class="btn btn-danger btn-xs" href="#">删除</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <ul class="pagination" style="float: left;">
            {{ page_number }}
        </ul>
    </div>

{% endblock %}

{% block js %}
    <script type="text/javascript">
        $(function () {
            // 页面框架加载完成后代码自动执行
            bindBtnAddEvent();

        })

        function bindBtnAddEvent() {
            // 捕获点击按钮
            $("#btnAdd").click(function () {
                // 清空上一次提交的错误信息
                $(".error-msg").empty();

                $.ajax({
                    url: '/task/add/',
                    type: "post",
                    data: $("#formAdd").serialize(),
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            alert("添加成功");
                            // 用JS刷新页面，显示添加成功后的数据
                            location.reload();
                        } else {
                            $.each(res.error, function (k, v) {
                                // console.log(k, v);
                                $("#id_" + k).next().text(v[0]);
                            })
                        }
                    }
                })
            })
        }
    </script>
{% endblock %}

web/templates/upload_form.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{{ title }}</h3>
        </div>
        <div class="panel-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for fields in form %}
                    <div class="form-group">
                        <label>{{ fields.label }}</label>
                        {{ fields }}
                        <span style="color: red">{{ fields.errors }}</span>
                    </div>
                {% endfor %}
                <button type="submit" class="btn btn-primary">提 交</button>
            </form>
        </div>
    </div>
{% endblock %}

web/templates/upload_list.html
{% extends 'layout.html' %}
{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" name="username">
        <input type="file" name="file">
        <input type="submit" value="提交">
    </form>
{% endblock %}

web/templates/user_list.html
{% extends 'search.html' %}

{% block content %}
    <div style="margin-bottom: 10px">
        <a class="btn btn-success" href="/user/add/">
            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
            新建用户
        </a>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            用户列表
        </div>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>序号</th>
                <th>用户名</th>
                <th>姓名</th>
                <th>性别</th>
                <th>所属部门</th>
                <th>账户余额</th>
                <th>入职时间</th>
                <th>是否为管理员</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in queryset %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ obj.account }}</td>
                    <td>{{ obj.name }}</td>
                    <td>{{ obj.get_gender_display }}</td>
                    <td>{{ obj.depart.title }}</td>
                    <td>{{ obj.balance }}</td>
                    <td>{{ obj.create_time|date:'Y-m-d' }}</td>
                    <td>{{ obj.get_admin_display }}</td>
                    <!-- 编辑操作 -->
                    <td>
                        <a class="btn btn-primary btn-xs" href="/user/{{ obj.id }}/edit/">编辑</a>
                        <a class="btn btn-danger btn-xs" href="/user/del/?nid={{ obj.id.hex }}">删除</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <ul class="pagination" style="float: left;">
        {{ page_number }}
    </ul>
{% endblock %}